### ISSUE TITLE
modifying the password db should take a lock

### ISSUE THREAD

**Issue by int-e** [al-caveman/nsapass#3]
At the moment, if the user adds two passwords concurrently, one of the updates will be lost, visually:

```
--- load() --------------------- update -- save() -- # this change survives
-------------- load() -- update -- save() ---------- # this change is lost
```

The easiest solution is to detect concurrent updates using a lock file and refuse to update in that case. (This is fine for interactive use; a solution that is suitable for scripting requires further thought.)

**Comment by int-e** [comment]
Using https://pypi.org/project/filelock/ may be an option (looks mature, but it is an external dependency on top of Python)

**Comment by al-caveman** [comment]
thanks.

unless there is a need for optimizing performance for automation by scripts, i personally think we better go with the simple global lock so that we preserve having a stupidly simple implementation to make auditing super easy.

plus, if we go with this simple global lock, we will also be able to simplify #2's `save(..)` function by removing all `tempfile` bits, and then simply use a fixed `.tmp` path, e.g. writing to `db.tmp` and `os.rename('db.tmp, 'db')`.

about the implementation of the locking mechanism, my initial thought is to stick to a pure-python solution, and to not worry about bad platforms such as windows.  this way, i guess we can have a simple solution using `fcntl`?

just some preliminary thoughts.  i could be wrong.  any better thoughts are welcome. it also depends on what platforms you use.

---

extra thoughts:  i think even for the scripting use, it would be fine to have a global lock, because the script will be only reading passwords.  a shared global lock can be concurrent and no limitation on the read-only use by scripts.

rarely a password is modified, or added.  so rarely an exclusive lock will be there.  in these rare cases, i think a script can wait a bit. i also doubt there is any sensible use case where a script needs to update passwords so aggressively to test the limits of a global exclusive lock.

**Comment by int-e** [comment]
See also #4.
